### ISSUE TITLE
DeprecationWarning: 'imghdr' is deprecated and slated for removal

### ISSUE THREAD

**Issue by jhanley634** [ydataai/ydata-profiling#1419]
### Current Behaviour

The imghdr module is deprecated in Python 3.11 by [PEP 594](https://peps.python.org/pep-0594/#imghdr) and is slated for removal in Python 3.13.
Ydata-profiling always imports it.

FYI, the streamlit folks recently addressed the identical environment regression: https://github.com/streamlit/streamlit/pull/7081

```
$  conda create -n ydata_env
...
$ (conda activate ydata_env && conda install -c conda-forge ydata-profiling)
...
$  (conda activate ydata_env && conda list | grep ydata && python --version && python -W error -c 'import ydata_profiling')
# packages in environment at /Users/jhanley/miniconda3/envs/ydata_env:
ydata-profiling           4.5.0              pyhd8ed1ab_0    conda-forge
Python 3.11.4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/site-packages/ydata_profiling/__init__.py", line 7, in <module>
    from ydata_profiling.compare_reports import compare
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/site-packages/ydata_profiling/compare_reports.py", line 12, in <module>
    from ydata_profiling.profile_report import ProfileReport
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/site-packages/ydata_profiling/profile_report.py", line 20, in <module>
    from visions import VisionsTypeset
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/site-packages/visions/__init__.py", line 3, in <module>
    from visions import types, typesets, utils
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/site-packages/visions/utils/__init__.py", line 4, in <module>
    from visions.utils.monkeypatches import imghdr_patch, pathlib_patch
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/site-packages/visions/utils/monkeypatches/__init__.py", line 1, in <module>
    from visions.utils.monkeypatches import imghdr_patch, pathlib_patch
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/site-packages/visions/utils/monkeypatches/imghdr_patch.py", line 2, in <module>
    from imghdr import tests
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/imghdr.py", line 9, in <module>
    warnings._deprecated(__name__, remove=(3, 13))
  File "/Users/jhanley/miniconda3/envs/ydata_env/lib/python3.11/warnings.py", line 514, in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
```

### Expected Behaviour

The `import` with `-W error` should succeed without warnings, just like `python -c 'import ydata_profiling'` succeeds.

### Data Description

[empty set]

### Code that reproduces the bug

```Python
(as above)
```

### pandas-profiling version

4.5.0

### Dependencies

```Text
$ (conda activate ydata_env &&  conda --version && conda list)
conda 23.7.2
# packages in environment at /Users/jhanley/miniconda3/envs/ydata_env:
#
# Name                    Version                   Build  Channel
attrs                     23.1.0             pyh71513ae_1    conda-forge
brotli                    1.0.9                hb7f2c08_9    conda-forge
brotli-bin                1.0.9                hb7f2c08_9    conda-forge
brotli-python             1.0.9           py311h814d153_9    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2023.7.22            h8857fd0_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0           py311h5fe6e05_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dacite                    1.8.0              pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
fonttools                 4.42.0          py311h2725bcf_0    conda-forge
freetype                  2.12.1               h3f81eb7_1    conda-forge
htmlmin                   0.1.12                     py_1    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagehash                 4.3.1              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4           py311hd2070f0_1    conda-forge
lcms2                     2.15                 h2dcdeff_1    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libblas                   3.9.0           17_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                hb7f2c08_9    conda-forge
libbrotlidec              1.0.9                hb7f2c08_9    conda-forge
libbrotlienc              1.0.9                hb7f2c08_9    conda-forge
libcblas                  3.9.0           17_osx64_openblas    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.18                 hac1461d_0    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           12_3_0_h97931a8_1    conda-forge
libgfortran5              12.3.0               hbd3c1fe_1    conda-forge
libjpeg-turbo             2.1.5.1              hb7f2c08_0    conda-forge
liblapack                 3.9.0           17_osx64_openblas    conda-forge
libopenblas               0.3.23          openmp_h429af6e_0    conda-forge
libpng                    1.6.39               ha978bb4_0    conda-forge
libsqlite                 3.42.0               h58db7d2_0    conda-forge
libtiff                   4.5.1                hf955e92_0    conda-forge
libwebp-base              1.3.1                h0dc2134_0    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               16.0.6               hff08bdf_0    conda-forge
markupsafe                2.1.3           py311h2725bcf_0    conda-forge
matplotlib-base           3.7.1           py311h2bf763f_0    conda-forge
multimethod               1.4                        py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  hf0c8a7f_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numpy                     1.23.5          py311h62c7003_0    conda-forge
openjpeg                  2.5.0                h13ac156_2    conda-forge
openssl                   3.1.2                h8a1eda9_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3           py311hab14417_1    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
phik                      0.12.3          py311h0482ae9_0    conda-forge
pillow                    10.0.0          py311h7cb0e2d_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pydantic                  1.10.12         py311h2725bcf_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.4          h30d4d87_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1           py311hd5badaa_0    conda-forge
pyyaml                    6.0             py311h5547dcb_5    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scipy                     1.10.1          py311h16c3c4d_3    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
statsmodels               0.14.0          py311h4a70a88_1    conda-forge
tangled-up-in-unicode     0.2.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tqdm                      4.66.0             pyhd8ed1ab_0    conda-forge
typeguard                 2.13.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
visions                   0.7.5              pyhd8ed1ab_0    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
wordcloud                 1.9.2           py311h2725bcf_1    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
ydata-profiling           4.5.0              pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h829000d_7    conda-forge
```
```


### OS

MacOS Monterey 12.6.8

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by Mr-MVP** [comment]
The package imghdr is going to deprecated and is slated for removal. It is mostly because it is have small amount of code with no maintainers. There are 2 ways to handle this issue

1. As imghdr is going to get removed we are given options of better, up-to-date and maintained libraries in the given link.

https://peps.python.org/pep-0594/#imghdr

Better libraries include filetype, pure-magic and python-magic. Implementing this instead of imghdr should resolve the issue as it is only due to imghdr getting removed.

2. We can setup the conda environment is a previous python version with the following command
`conda create --name myenv python=3.10`
Any code below python 3.11 should work fine and the as it is after python 3.11 that issue started rising. 

I personally would suggest to shift to newer libraries as it would free our restrictions of setting up python in previous versions as well as the code becoming mode usable in upcoming updates. 

Hope I was able to help.

**Comment by firegate22** [comment]
@WilliamJudge94 
It's still present via the module visions, isn't it?

.venv/lib/python3.12/site-packages/visions/utils/monkeypatches/imghdr_patch.py:2

**Comment by WilliamJudge94** [comment]
> @WilliamJudge94 
> It's still present via the module visions, isn't it?
> 
> .venv/lib/python3.12/site-packages/visions/utils/monkeypatches/imghdr_patch.py:2

@firegate22 I don't see this directory on the most recent codebase. It might be because I am on my phone. Could you provide a link to this specific location within the current state of the repo?
